- repository: "actions/checkout"
  permissions:
    contents: "read"
- repository: "actions/labeler"
  permissions:
    contents: "read"
    pull-requests: "write"
- repository: "aws-actions/configure-aws-credentials"
  permissions:
    id-token: "write"
