name: go

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20'
          check-latest: true
          cache: true
      - name: lint code
        uses: golangci/golangci-lint-action@v3
        with:
          skip-pkg-cache: true
